controller:
  mode_pr: 0
  mode_machine: 0

FSM:
  _:
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: Velocity
    WindSummer:
      id: 101
      type: Track
    GeneralTracker:
      id: 201
      type: Track
    # PokerFace:
    #   id: 102
    #   type: Track

  Passive:
    transitions:
      FixStand: LT + up.on_pressed
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,
      0,
      1,1,1,1,1,
      0,0,
      1,1,1,1,1,
      0,0,
      1,1,
      0,0
    ]
    kd: [
      8,8,8,8,10,10,
      8,8,8,8,10,10,
      8,8,
      0,
      2,2,2,2,2,
      0,0,
      2,2,2,2,2,
      0,0,
      2,0.5,
      0,0
    ]

  FixStand:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    kp: [
      200,200,200,200,220,220,
      200,200,200,200,220,220,
      200,200,
      0,
      40,40,40,40,40,
      0,0,
      40,40,40,40,40,
      0,0,
      40,10,
      0,0
    ]
    kd: [
      8,8,8,8,10,10,
      8,8,8,8,10,10,
      8,8,
      0,
      2,2,2,2,2,
      0,0,
      2,2,2,2,2,
      0,0,
      2,0.5,
      0,0
    ]
    ts: [0, 3]
    qs: [
      [],
      [
        -0.15,0,0,0.325,-0.15,0,
        -0.15,0,0,0.325,-0.15,0,
        0,0,
        0,
        0,0.1745,0,1.5708,0,
        0,0,
        0,-0.1745,0,1.5708,0,
        0,0,
        0,0,
        0,0
      ]
    ]

  Velocity:
    transitions:
      Passive: LT + B.on_pressed
      WindSummer: LT(2s) + down.on_pressed
      GeneralTracker: LT(2s) + up.on_pressed
      # PokerFace: LT(2s) + right.on_pressed
    policy_dir: config/policy/velocity/v0

  WindSummer:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    policy_dir: config/policy/dance/wind_summer
    policy_file: policy.onnx
    deploy_file: deploy.yaml
    motion_file: config/policy/dance/wind_summer/params/wind_summer.et1trk
    fps: 50
    no_global_mode: true
    use_motion_root_command: true
    use_motion_velocity_command: false

  GeneralTracker:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    policy_dir: config/policy/general_tracker/et1Tracker
    policy_file: policy.onnx
    deploy_file: deploy.yaml
    motion_file: config/policy/general_tracker/et1Tracker/params/default.et1trk
    fps: 50
    no_global_mode: true
    use_motion_root_command: false
    use_motion_velocity_command: false
    debug_dump_first_frame: true
    debug_dump_dir: debug/et1_track_first_frame

  # PokerFace:
  #   transitions:
  #     Passive: LT + B.on_pressed
  #     Velocity: RB + X.on_pressed
  #   policy_dir: config/policy/dance/poker_face
  #   policy_file: policy.onnx
  #   deploy_file: deploy.yaml
  #   motion_file: config/policy/dance/poker_face/params/poker_face.et1trk
  #   fps: 50
  #   no_global_mode: true
  #   use_motion_root_command: true
  #   use_motion_velocity_command: false
